server:
  port: 9090

spring:
  application:
    name: spring-consul
  zipkin:
    enabled: false
  mvc:
    log-request-details: true
  datasource:
    url: "jdbc:mysql://localhost:3307/spring-training?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false"
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
        health-check-critical-timeout: "5m"
        health-check-path: /actuator/health
        health-check-interval: 10s
        hostname: DESKTOP-GJ9JFOE.mshome.net

info:
  application:
    name: Spring Consul
    description: Simple SpringBoot application with Service Discovery

management:
  endpoint:
    health:
      show-details: always
    consul:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  oauth:
    authorizationUrl: http://localhost:8080/realms/training/protocol/openid-connect/auth
    tokenUrl: http://localhost:8080/realms/training/protocol/openid-connect/token


logging:
  level:
    org.springframework.web: TRACE