server:
  ssl:
    enabled: true
    key-store: classpath:server.jks
    key-store-password: changeit
    key-store-type: JKS
    key-alias: thinktech


spring:
  cloud:
    consul:
      discovery:
       scheme: https
       health-check-tls-skip-verify: true