server:
  port: 9090

spring:
  application:
    name: spring-consul
  zipkin:
    enabled: false
  mvc:
    log-request-details: true
  datasource:
    url: "jdbc:mysql://localhost:3307/spring-training?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false"
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
        health-check-critical-timeout: "5m"
        health-check-path: /actuator/health
        health-check-interval: 10s
        hostname: DESKTOP-GJ9JFOE.mshome.net
        catalog-services-watch:
          enabled: false

info:
  application:
    name: Spring Consul

management:
  health:
    consul:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.web: TRACE